server:
  port: 8080

spring:
    thymeleaf:
      cache: false
      mode:  LEGACYHTML5
    datasource:
      name: test
      url: jdbc:mysql://115.159.149.177:3306/db_training
      username: xuw
      password: xuw@123
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: wall,stat
      initial-size: 1
      max-active: 3
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
mybatis:
  mapper-locations: classpath*:**/*Mapper.xml
  type-aliases-package: com.example.model
  configuration:
      mapUnderscoreToCamelCase: true
#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
#  notEmpty: true

