server:
  port: 90
spring:
    application:
      name: jutongji
    datasource:
      name: ts
      url: jdbc:mysql://115.159.149.177:3306/jutongji?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
      username: xuw
      password: xuw@123
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: wall,stat
      initial-size: 1
      max-active: 3
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
    jpa:
      open-in-view: true
      show-sql: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      #content-type: text/html
      strategy:
        content:
          enabled: true
          paths: /**
mybatis:
  mapper-locations: classpath*:**/*Mapper.xml
  type-aliases-package: com.example.model
  configuration:
      mapUnderscoreToCamelCase: true
logging:
    file: /data/logs/${spring.application.name}.log
    level:
      root: info
      com:
        jutongji:
            dao: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss:SSS}  [%thread] %-5level %logger{36}.%M [%L] - [%X{TRACE_ID}] %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss:SSS} [%thread] %-5level %logger{36} - [%X{TRACE_ID}] %msg%n"
#thymelea模板配置

#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
#  notEmpty: true

